# Azure Pipelines Configuration
# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: "ubuntu-16.04"

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    displayName: Install Node
    inputs:
      versionSpec: "10.x"

  - script: yarn install
    displayName: Install Dependencies

  - script: yarn test:junit
    displayName: Run Unit Tests

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: "junit.xml"
      testRunTitle: "Results for Unit Tests"
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage/cobertura-coverage.xml"

  - script: yarn typedoc
    displayName: Generate TypeDoc Wiki

  - script: yarn build:docs
    displayName: Build Docs

  - script: cd docs/dist && git init . && git remote add origin git@github.com:vincentfiestada/acrylic.git && git add -A
    displayName: Staging Commit

  - script: cd docs/dist && git config user.name 'Azure Pipelines' && git config user.email 'vincentfiestada@hotmail.com'
    displayName: Configure Git

  - script: cd docs/dist && git commit -m 'build docs'
    displayName: Commit

  - script: cd docs/dist && git push -u origin master:gh-pages --force
    displayName: Push to GitHub
