# Azure Pipelines Configuration
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts

jobs:
  - job: tests
    displayName: Run Tests
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        displayName: Install Node
        inputs:
          versionSpec: "10.x"

      - script: yarn install
        displayName: Install Dependencies

      - script: yarn test:junit
        displayName: Run Unit Tests

      - script: npx commitlint -f origin/master -t HEAD
        displayName: Check commit messages

      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "junit.xml"
          testRunTitle: "Results for Unit Tests"
        condition: succeededOrFailed()

      - task: PublishCodeCoverageResults@1
        displayName: Publish Code Coverage
        inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage/cobertura-coverage.xml"

  - job: publishDocs
    dependsOn: tests
    displayName: Publish Docs
    pool:
      vmImage: 'Ubuntu-16.04'
    condition: and(succeeded('tests'), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    steps:
      - task: NodeTool@0
        displayName: Install Node
        inputs:
          versionSpec: "10.x"

      - script: yarn install
        displayName: Install Dependencies
        
      - script: yarn typedoc
        displayName: Generate Wiki

      - script: yarn build:docs && cp web.config docs/dist/
        displayName: Build Docs

      - task: FtpUpload@1
        displayName: Upload to Azure
        inputs:
          credentialsOption: inputs
          serverEndpoint:
          serverUrl: ftps://waws-prod-sg1-029.ftp.azurewebsites.windows.net/site/wwwroot
          username: 'acrylic\$acrylic'
          password: $(ftp.password)
          rootDirectory: docs/dist
          filePatterns: "**"
          overwrite: true
          preservePaths: true
          remoteDirectory: /site/wwwroot
          clean: false
          cleanContents: true
          trustSSL: false
