# Azure Pipelines Configuration
# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: "ubuntu-16.04"

steps:
  - task: NodeTool@0
    displayName: Install Node
    inputs:
      versionSpec: "10.x"

  - script: yarn install
    displayName: Install Dependencies

  - script: yarn test:junit
    displayName: Run Unit Tests

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: "junit.xml"
      testRunTitle: "Results for Unit Tests"
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage/cobertura-coverage.xml"
